name: hbitolar
description: "Habitracker é o seu parceiro diário para construir e manter hábitos saudáveis, transformando a jornada de autodesenvolvimento em uma experiência recompensadora e divertida."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  google_sign_in: ^6.1.0
  provider: ^6.1.2
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
