// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsIVqdIJuYIvxYw-bjsf49F0Ftxb8gJuM',
    appId: '1:38550434871:web:395ff12ead9f828968fbb2',
    messagingSenderId: '38550434871',
    projectId: 'habitracker-3f9b4',
    authDomain: 'habitracker-3f9b4.firebaseapp.com',
    storageBucket: 'habitracker-3f9b4.firebasestorage.app',
    measurementId: 'G-4W56JFRRYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsIVqdIJuYIvxYw-bjsf49F0Ftxb8gJuM',
    appId: '1:38550434871:android:395ff12ead9f828968fbb2',
    messagingSenderId: '38550434871',
    projectId: 'habitracker-3f9b4',
    storageBucket: 'habitracker-3f9b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIVqdIJuYIvxYw-bjsf49F0Ftxb8gJuM',
    appId: '1:38550434871:ios:395ff12ead9f828968fbb2',
    messagingSenderId: '38550434871',
    projectId: 'habitracker-3f9b4',
    storageBucket: 'habitracker-3f9b4.firebasestorage.app',
    iosBundleId: 'com.habitracker.app',
  );
}
